services:
  unisonmusic_api:        
    image: ghcr.io/dvvtech/unisonmusic-back:latest      
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod      
    networks:
      - public-network5
    secrets:
      - Jwt__Key
      - GoogleRecaptcha__SecretKeyForOfftube
      - S3CloudConfig__TenantId      
      - S3CloudConfig__AccessKey
      - S3CloudConfig__SecretKey
      - unisonmusic_connection_string
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:      
        - "traefik.enable=true"      
        - "traefik.http.routers.unisonmusic-api.rule=Host(`api.unisonmusic.ru`) && PathPrefix(`/`)"
        - "traefik.http.routers.unisonmusic-api.entrypoints=websecure"      
        - "traefik.http.routers.unisonmusic-api.tls.certresolver=letsencrypt"     
        - "traefik.http.services.unisonmusic-api.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.unisonmusic-stripprefix.stripprefix.prefixes=/"
        - "traefik.http.routers.unisonmusic-api.middlewares=unisonmusic-stripprefix"

networks:
  public-network5:
    external: true

secrets:
  Jwt__Key:
    external: true  
  GoogleRecaptcha__SecretKeyForOfftube:
    external: true
  S3CloudConfig__TenantId:
    external: true
  S3CloudConfig__AccessKey:
    external: true
  S3CloudConfig__SecretKey:
    external: true
  unisonmusic_connection_string:
    external: true